### ISSUE TITLE
Primary Key for Course is incorrect

### ISSUE THREAD

**Issue by griffine** [smacademic/project-GEEKS#16]
The current primary key for a course is its name/number (i.e. 'CS170). However, after further inspection of WCSU's OpenClose course listings, a course's name/number value is not unique. 

Health Promotion and Exercise courses may have the same name/number (HPX177), but different titles. 
For example, both of the following exist in the listing for Spring 2019:

- HPX177, Fit for Life - Tai Chi 
- HPX177, Fitness for Life - Yoga
 
The primary key for Course could be changed to include both the name/number and the title to fix this issue. Alternatively, a new 'ID' attribute with a value such as INT or SERIAL could be added as the primary key. Either way, fixing this issue entails fixing and updating the Conceptual Schema, Logical Schema, and createTables.sql.

**Comment by griffine** [comment]
@kozlowskik @fitz-cris @DasilvaB Do you guys have any preference of one over the other? If not, I'd like to implement the primary key as being the combination of the name/number and title. 

The only issue I can see with this, however, is that this does not protect against accidental duplicate entries with similar but not exactly the same title text. For example, both the courses 'CS170, Language C++' and 'CS170, Intro to Language C++' could both exist even though they are most likely the same course. Using a new 'ID' attribute does not protect against this either. We can push past this problem with the varying titles if we assume that the person entering the course has prior knowledge as to what is already in the DB, however I do not know if that is the best decision to make.

**Comment by kozlowskik** [comment]
I would agree with how you want to change the primary key to be the combination of the course name/number and the title

**Comment by fitz-cris** [comment]
In order to minimize the likelihood of duplicate entries, we could potentially use predictive text in the web UI to show the user similar courses already present in the DB.

**Comment by DasilvaB** [comment]
Hmm, that issue is pretty big. We could go with the fix you have and potentially use predictive text but I feel like thats a bandaid fix. Relying on the user to not make a mistake is usually something we should heavily try to avoid if theres another possible solution.
