### ISSUE TITLE
[Server Bug] Unexpected Error Token when trying to login to Gradebook

### ISSUE THREAD

**Issue by kozlowskik** [smacademic/project-GEEKS#32]
## Issue Information

**Describe the bug**  
When trying to log into the GB web app, when all user information is presented and the submit button is pressed,  a console error of unexpected token is shown and the user is not allowed to log into the application.

**Location of Error**  
`src/webapp/client/index.js` line 167

**To Reproduce**
1. Open Gradebook in a browser
2. Enter in all of the user information: `username`, `password`, and `DB Info`
3. Click on Login

**Expected behavior**
Login should be processed without error and page contents should change.

**Screenshots**
<img width="1440" alt="screen shot 2019-03-04 at 4 16 42 pm" src="https://user-images.githubusercontent.com/43095923/53763519-023d4900-3e99-11e9-90fe-a20e07f91516.png">

***

## System Information
**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version Latest Update

***

## Additional Information

**Additional context**

**Comment by fitz-cris** [comment]
This issue is due to an error in line 167 of index.js, an extraneous else was inserted. A hotfix will be pushed shortly.
