### ISSUE TITLE
Some PRs are including extra commits

### ISSUE THREAD

**Issue by griffine** [smacademic/project-GEEKS#34]
Some PRs (listed below) are including unrelated / past commits and PRs. 

Examples of this are: 

- #33 

- #24 

- #26 

If any others are found, this will be edited, and they will be added in later.

A common aspect within the PRs is that they all merge into the 'features' branch. The issue may be caused by the timing and order in which the branches were branched/merged in relation to the 'dev' and 'features' branches.

**Comment by griffine** [comment]
I possible helpful feature that I found was a map of all the branches. It can be found in the 'Insights' tab and then within that, under the 'Network' tab. However, it is very difficult to fully understand what is going on in the map since some of the branches have similar colors as well as overlap.

**Comment by fitz-cris** [comment]
At a glance, I think the problem stems from the branches we intend to merge into features being based on the hot-fixes branch, or in the case of #33, the dev branch. I would suggest that all intended features sub branches be based on the main features branch. However, this might lead to the extra commits simply being added when we push from features to dev, though this remains to be seen.
