### ISSUE TITLE
[Server Bug] addCourseMgmt.sql does not Successfully Run

### ISSUE THREAD

**Issue by kozlowskik** [smacademic/project-GEEKS#43]
## Issue Information

**Describe the bug**
There are 2 issues that arise when trying to run the script via **psql** shown here:
`gradebook=# \i 'addCourseMgmt.sql' 
	psql:addCourseMgmt.sql:36: ERROR:  syntax 	error at or near "RETURN"  
	LINE 2: RETURN VOID AS
        	^  
	psql:addCourseMgmt.sql:62: ERROR:  	mismatched parentheses at or near ";"  
	LINE 10: ...M Course WHERE Course.Number = 	Num AND Course.Title = Title;  
                                    ^  `

**Location of Error**  
`src/db/addCourseMgmt.sql` Lines **17** and **25**

**To Reproduce**

**Expected behavior**
SQL script should run without any errors and DB functions should be created.

**Screenshots**

***

## System Information
**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version Latest Update
***

## Additional Information

**Additional context**

**Comment by DasilvaB** [comment]
There's a closing parenthesis that needs to be removed on line 25. Simple fix if anyone can get to it.

**Comment by kozlowskik** [comment]
I can address it over spring break along with any of the other issues i submit today

**Comment by griffine** [comment]
I just saw this issue now after creating PR #47 . This PR should address and fix this issue.
