### ISSUE TITLE
[Server Bug] Adding and Removing Courses Does Not Work

### ISSUE THREAD

**Issue by kozlowskik** [smacademic/project-GEEKS#44]
## Issue Information

**Describe the bug**
When trying to add or remove a course from the application, an error is displayed stating that either "The course is already represented"(add a course) or that "the course does not exist"(remove a course).  
<br>
All of the fields that were required for the application to work were filled in properly and the same two course name/number and Title were used:  
`CS170` `Language C++`  
`EX100` `Example Course 100`  
Both courses had the same outcome when trying to add or remove the course

**Location of Error**  
It could be either in:  
`index.js` or `addCourseMgmt.sql` or `GradebookServer.js`

**To Reproduce**
1. Log into Gradebook
2. Click on Course Management
3. Click on Add A Course
4. Enter in one of 

**Expected behavior**
When adding a course, as long as the course did not exist already, then the course should have been added to the system.  
When removing the course, as long as the course did exist, then the course should have been removed from the system.

**Screenshots**

***

## System Information
**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version Latest Updates

***

## Additional Information

**Additional context**

**Comment by griffine** [comment]
I believe there are a few issues with the addCourseMgmt.sql. I will address them shortly.
