### ISSUE TITLE
[Feature Request] Implement Report on Courses Feature

### ISSUE THREAD

**Issue by kozlowskik** [smacademic/project-GEEKS#50]
**Please Describe the Feature**
This would implement FR 8.4 from Gradebook (Report on Courses)
  
**Does the Feature Require a Database Change?**  
Please check one of the boxes:  
- [x] Yes
- [ ] No

**If Yes, Please describe the change that would be needed in detail. (Include any screenshots or supporting material if needed)**  
Searching functions to find a specific Course or set of courses.
  

**Does the Feature Require a Web server Change?**  
Please check one of the boxes:  
- [x] Yes
- [ ] No
  
**If yes, please describe the Web server change needed**  
The ability to communicate all of the search attributes to the appropriate DB function
  

**Does the Feature Require a User Interface Change?**  
Please check one of the boxes:  
- [x] Yes
- [ ] No
  
**If yes, Please describe the changes that are needed and include any screenshots or supporting documents**  
A table view that would be dynamically populated with the courses in the DB needs to be added as well as all of the search boxes need to be implemented as well so that an end user can narrow results down to a certain set of courses.
  
***

**Additional context**
Add any other information here.

**Comment by kozlowskik** [comment]
Added in the dynamic table for viewing courses. Not sure if I am missing anything else needed to report on courses. @fitz-cris could you take a look at `index.html` in the  `update-ui-for-view-update` branch to see if there is anthing missing that the backend will need?

**Comment by fitz-cris** [comment]
At a cursory glance, index.html looks fine for now, but if changes need to be made going forwards I will post a follow up comment.
