### ISSUE TITLE
System Test Documentation Does Not Exist

### ISSUE THREAD

**Issue by kozlowskik** [smacademic/project-GEEKS#55]
When looking at the program as a whole, it does not seem that there is any documentation of what the expected behavior of Gradebook is so that the end user can verify after installation that the system is working as we intend it to work.  
This would include all of the areas that we are working on from email verification, input fields expected inputs and information being returned to the user.  
***
A *markdown* file would be the best-suited type of file to write for this testing document because it would be fairly simple to include all of the information that is needed for the testing. It would also make it simpler to add more information to the document as the continuation of this project continues over the course of development. Finally, at the end of the semester, the document can be published as a **PDF** so that it can be easily downloaded and printed for an end user to use for comparison.  
This *markdown* file would live in the `tests` directory in the repo under what would be a new subdirectory called `system_testing`

**Comment by DasilvaB** [comment]
This will be pushed back to next milestone

**Comment by kozlowskik** [comment]
The beginning of the documentation has now been written in #94. There is more work that needs to be done so that the document has information for all working portions of the program.
