### ISSUE TITLE
[Server Bug] Courses table does not show up

### ISSUE THREAD

**Issue by fitz-cris** [smacademic/project-GEEKS#69]
## Issue Information

**Describe the bug**
When the course management tab is selected, a dynamically populated table of all the courses that are currently within the system should be displayed. However, this table does not appear.

**Location of Error**  
index.js most likely.

**To Reproduce**
Go to courses tab.

**Expected behavior**
A dynamically populated table of courses should appear and be updated. 

**Screenshots**

***

## System Information
**Desktop (please complete the following information):**
 - OS: Windows 7
 - Version 0.30

***

**Comment by DasilvaB** [comment]
I think the issue is on line 489, the courses object is not being sent back.
