### ISSUE TITLE
Current Implementation of 'Course' Table Needs Updating

### ISSUE THREAD

**Issue by griffine** [smacademic/project-GEEKS#7]
The sub-requirement of adding a course for manage courses lists the attributes that a course should have:

- name/number
- title
- number of credits
- offering departments

The current implementation of a course in the Conceptual Schema, Logical Schema, and createTables.sql script only allows for a name/number and a title. The attributes for credits and offering departments need to be added. 

**To Do:** 
- [ ] Update Conceptual Schema
- [ ] Update Logical Schema
- [ ] Update createTable.sql

**Comment by fitz-cris** [comment]
In the current implementation, the course number includes a two to three letter department designation, I.E. "CS170". As such, we might not need an attribute to categorize the offering departments. The only issue I can see arising with this would be dual department courses, such as CS/MAT 359, or some others. To combat this we could increase the number of characters in the "number" attribute. As well, if we do implement filter or search functionality as we discussed, this may complicate separating courses out by department.

**Comment by griffine** [comment]
I agree and think that extending the number of characters could complicate the sorting/filtering by department functionality, though it could still work in the long run. Alternatively, a one two-three character long attribute can be added to course to store a second department name or NULL if non-applicable.

**Comment by fitz-cris** [comment]
With the merge of PR 14 (Update 'Course' Implementation), this issue is now completed.
