### ISSUE TITLE
[Feature Request] View and Modify a Section

### ISSUE THREAD

**Issue by griffine** [smacademic/project-GEEKS#81]
**Please Describe the Feature**

- View a section: allowing the user to view all information pertaining to a specific section as well as a general list of all the sections
- Modify a section: allowing the user to update attributes of a given section

  
**Does the Feature Require a Database Change?**  
Please check one of the boxes:  
- [x] Yes
- [ ] No

**If Yes, Please describe the change that would be needed in detail. (Include any screenshots or supporting material if needed)**  
Create DB function to allow for updating a row in the Section table.
Modify the current DB function that allows the user to view a row in the Section table's information.
  

**Does the Feature Require a Web server Change?**  
Please check one of the boxes:  
- [x] Yes
- [ ] No
  
**If yes, please describe the Web server change needed**  
Pass modifications of a Section to the database
  

**Does the Feature Require a User Interface Change?**  
Please check one of the boxes:  
- [x] Yes
- [ ] No
  
**If yes, Please describe the changes that are needed and include any screenshots or supporting documents**  
Currently up for discussion - no set UI plans as of now
  
***

**Comment by griffine** [comment]
**For the modify requirement, which fields do we want to allow the user to change?** 

The current modifySection(...) DB function only allows the user to modify SectionNumber (if it does not conflict with an existing section), Schedule, Capacity, Location, and MidtermDate. 

Instructor modification has been left out due to 'Assign Instructors' being its own requirement (FR11.4). I do not think a user should be allowed to modify the ID, however, I am unsure about Term, Course, CRN, StartDate, and EndDate. 

**Here are some thoughts I had regarding those, and please let me know what you guys think:** 
- **Term and Course:** I think that having them be modifiable would be overstepping into adding a section's functionality. Adding SectionNumber might also fall into this category, but I'm not sure. EDIT: I know that for Course we allowed the user to modify the PK values, so we can do the same for section as well if we want.

- **CRN:** I think that this should be modifiable, however I think that first it needs to added to the `UNIQUE(Term, Course, SectionNumber)` that the Section table has. I don't think that CRNs can repeat in a single term, but can repeat over multiple terms thus making it unique with the attributes in the uniqueness constraint. If added to the constraint, it could fall into the same category as modifying SectionNumber. 

- **StartDate and EndDate:** I don't know if these are section specific or term specific. If section specific, then I think they should be modifiable.

**Comment by DasilvaB** [comment]
I agree CRN should be modifiable as well. Pretty sure start/end dates are term specific so that isn't something we should handle. As for term and course, I don't see a big issue with allowing the user to update this information, we can see what everybody else thinks and discuss it more.
