### ISSUE TITLE
[Client Bug]Courses Table Edit

### ISSUE THREAD

**Issue by fitz-cris** [smacademic/project-GEEKS#95]
## Issue Information
The edit buttons within the courses table do not properly function

**To Reproduce**
Please list all of the steps that were taken that led up to this issue:
-go to the course management page
-click an edit button next to a currently existing course

**Expected behavior**
Submit and cancel buttons should appear

**Screenshots**

***

## System Information

Please fill in only the section that applies to your issue.  

**Desktop (please complete the following information):**
 - OS: Windows 7
- Browser: Chrome

**Comment by fitz-cris** [comment]
Courses without spaces in their titles function as intended.

**Comment by kozlowskik** [comment]
This was fixed in one of the previous releases we had. Issue no longer is required to be open because the issue has been resolved and the courses table now is able to be edited with titles that include spaces.
